[files]
extend-exclude = ["docs/fr/**"]

[default]
extend-words = { "Encyption" = "Encyption", "complet" = "complet", "ba" = "ba", "mis" = "mis" }
extend-identifiers = { "ratatui" = "ratatui", "fo" = "fo" }
