# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sigmacatch contributors

[workspace]
resolver = "2"
members = [
    "sigmacatch-win",
    "sigmacatch-lnx",
    "crates/sigmacatch-runner",
    "crates/sigmacatch-regression",
    "crates/sigmacatch-detection",
    "crates/sigmacatch-types",
    "crates/sigmacatch-config",
    "crates/sigmacatch-logger",
    "crates/input-windows-evtx",
    "crates/sigmacatch-evtx-writer",
    "crates/sigmacatch-rule",
    "crates/sigmacatch-repo",
]

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "MIT"

[profile.release]
strip = true
lto = true
codegen-units = 1
