# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sigmacatch contributors

[workspace]
resolver = "2"
members = [
    "sigmacatch",
    "crates/sigmacatch-regression",
    "crates/sigmacatch-detection",
    "crates/sigmacatch-types",
    "crates/sigmacatch-config",
    "crates/sigmacatch-logger",
    "crates/input-evtx",
    "crates/input-windows-channels",
    "crates/sigmacatch-rule",
    "crates/sigmacatch-repo",
    "tools",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
