# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 sigmacatch contributors

[package]
name = "input-evtx"
version = "0.3.1"
edition = "2021"
description = "Parse EVTX files into sigmacatch_types::Event objects"
license = "MIT"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
evtx = "0.12"
sigmacatch-types = { path = "../sigmacatch-types" }
tokio = { version = "1", features = ["sync"] }
