// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 sigmacatch contributors

use anyhow::Result;
use grit_lib::objects::ObjectId;
use std::path::Path;
use tracing::{info, warn};

use crate::git;

/// Branch naming convention: sigmacatch-contrib/YYYYMMDD
pub fn create_branch_name() -> String {
    let date = chrono::Local::now().format("%Y%m%d");
    format!("sigmacatch-contrib/{}", date)
}

/// Create a new branch from origin/master (or origin/main fallback).
/// If the branch already exists locally, switches to it without error.
pub fn create_branch(repo_path: &Path, branch_name: &str) -> Result<()> {
    let git_dir = repo_path.join(".git");
    git::create_branch(&git_dir, branch_name)
}

/// Push the current branch to the given remote using grit-lib HTTP.
/// Fetches remote state first, then pushes only if safe:
/// - New branch (remote doesn't exist) → normal push
/// - Local ahead of remote → normal push (fast-forward)
/// - Remote ahead or diverged → skip with warning (no force)
pub fn push_branch(
    repo_path: &Path,
    branch_name: &str,
    remote: &str,
    config_token: &str,
) -> Result<()> {
    let git_dir = repo_path.join(".git");

    let token = resolve_push_token(Some(config_token))?;
    let http_client = git::AuthHttpClient::new(token)?;

    let remote_url = read_remote_url(&git_dir, remote)?;

    // Verify HEAD matches the branch we intend to push
    let head_content = std::fs::read_to_string(git_dir.join("HEAD"))?;
    let expected_ref = format!("ref: refs/heads/{}\n", branch_name);
    if head_content != expected_ref {
        anyhow::bail!(
            "HEAD is not on branch '{}' (HEAD: {}). Refusing to push.",
            branch_name,
            head_content.trim()
        );
    }

    // Fetch the specific branch from remote
    let fetch_opts = grit_lib::transfer::FetchOptions {
        refspecs: vec![format!(
            "+refs/heads/{}:refs/remotes/{}/{}",
            branch_name, remote, branch_name
        )],
        ..Default::default()
    };
    let _fetch_outcome = grit_lib::transport::http::http_fetch(
        &http_client,
        &git_dir,
        &remote_url,
        &fetch_opts,
        &mut grit_lib::fetch::NoProgress,
    )
    .map_err(|e| anyhow::anyhow!("Failed to fetch branch '{}': {}", branch_name, e))?;

    // Check if remote tracking branch exists
    let remote_ref_name = format!("refs/remotes/{}/{}", remote, branch_name);
    let remote_exists = git::read_loose_or_packed_ref(&git_dir, &remote_ref_name).is_some();

    if !remote_exists {
        return git::push_branch(&http_client, &git_dir, &remote_url, branch_name);
    }

    // Read local branch OID
    let local_ref = format!("refs/heads/{}", branch_name);
    let local_oid_str = git::read_loose_or_packed_ref(&git_dir, &local_ref)
        .ok_or_else(|| anyhow::anyhow!("Branch '{}' not found locally", branch_name))?;
    let local_oid = ObjectId::from_hex(&local_oid_str)
        .map_err(|e| anyhow::anyhow!("Invalid OID for branch '{}': {}", branch_name, e))?;

    // Read remote tracking OID
    let remote_oid_str =
        git::read_loose_or_packed_ref(&git_dir, &remote_ref_name).ok_or_else(|| {
            anyhow::anyhow!(
                "Remote tracking ref '{}' not found after fetch",
                remote_ref_name
            )
        })?;
    let remote_oid = ObjectId::from_hex(&remote_oid_str)
        .map_err(|e| anyhow::anyhow!("Invalid remote OID '{}': {}", remote_oid_str, e))?;

    if local_oid == remote_oid {
        info!("Branch '{}' is already up to date with remote", branch_name);
        return Ok(());
    }

    // Check if remote is ancestor of local (fast-forward possible)
    let is_ancestor = match git::is_ancestor(&git_dir, remote_oid, local_oid) {
        Ok(v) => v,
        Err(e) => {
            warn!("Failed to check merge base: {}. Skipping push.", e);
            return Ok(());
        }
    };

    if is_ancestor {
        return git::push_branch(&http_client, &git_dir, &remote_url, branch_name);
    }

    // Remote is ahead or diverged → skip, no force
    let local_hex = local_oid.to_hex();
    let remote_hex = remote_oid.to_hex();
    warn!(
        "Branch '{}' has diverged from remote (local: {}, remote: {}). \
         Skipping push — merge or rebase manually before next run.",
        branch_name,
        &local_hex[..12.min(local_hex.len())],
        &remote_hex[..12.min(remote_hex.len())]
    );
    Ok(())
}

/// Reads a remote URL from a git config file.
/// Limitations: does not handle line continuation (`\` at EOL),
/// comments (`;` or `#`), or multi-line values.
/// Acceptable for the simple configs generated by this tool.
fn read_remote_url(git_dir: &Path, remote: &str) -> Result<String> {
    let config_path = git_dir.join("config");
    let content = std::fs::read_to_string(&config_path)?;
    let target_section = format!("[remote \"{}\"]", remote);
    let alt_section = format!("[remote {}]", remote);

    let mut in_section = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == target_section || trimmed == alt_section {
            in_section = true;
        } else if in_section {
            if trimmed.starts_with('[') {
                in_section = false;
            } else if let Some(eq_pos) = trimmed.find('=') {
                let key = trimmed[..eq_pos].trim();
                if key == "url" {
                    let value = trimmed[eq_pos + 1..].trim();
                    return Ok(value.trim_matches('"').to_string());
                }
            }
        }
    }
    anyhow::bail!("No URL found for remote '{}' in config", remote)
}

fn resolve_push_token(config_token: Option<&str>) -> Result<Option<String>> {
    if let Some(t) = config_token {
        let trimmed = t.trim();
        if !trimmed.is_empty() {
            return Ok(Some(trimmed.to_string()));
        }
    }
    if let Ok(t) = std::env::var("GITHUB_TOKEN") {
        let trimmed = t.trim();
        if !trimmed.is_empty() {
            return Ok(Some(trimmed.to_string()));
        }
    }
    anyhow::bail!(
        "No GitHub token. Set github_token in config.yaml or GITHUB_TOKEN env var. \
         Create a token at https://github.com/settings/tokens"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_branch_name_format() {
        let name = create_branch_name();
        assert!(name.starts_with("sigmacatch-contrib/"));
        assert_eq!(name.len(), "sigmacatch-contrib/".len() + 8);
        let date_part = &name["sigmacatch-contrib/".len()..];
        assert_eq!(date_part.len(), 8);
        assert!(date_part.chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_create_branch_name_is_date_based() {
        let name1 = create_branch_name();
        let name2 = create_branch_name();
        assert_eq!(name1, name2);
    }
}
